@extends('Layouts.App')
@section('title')

    <title>Yayınlar | Prof. Dr. Faruk Ayhan BAŞÇİFTÇİ | Ortodonti Uzmanı, Konya</title>
    
@endsection
@section('content')

    <div style="margin-top: -100px;" id="home_container" class="home_container">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="home_content">
                        <div class="home_title">.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

    <!-- About -->

    <div id="about" style="margin-top: 0px;" class="about">
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <div class="section_title">Yayınlar</div>


                </div>
            </div>
            <div class="row about_row row-eq-height mt-lg-4 mt-4">
                <div class="col-lg-12">

                    <div class="about_text_highlight">


                        <div class="tab row">
                            <button  class="tablinks col-lg-3 col-6 active " onclick="openCity(event, 'tab1')">Ulusal Bilimsel Toplantılarda Sunulan Bildiriler</button>
                            <button class="tablinks col-lg-3 col-6 " onclick="openCity(event, 'tab2')">Ulusal Dergilerde Yayınlanmış Makaleler</button>
                            <button class="tablinks col-lg-3 col-6 " onclick="openCity(event, 'tab3')">Uluslararası Bilimsel Toplantılarda Sunulan Bildiriler</button>
                            <button class="tablinks col-lg-3 col-6 " onclick="openCity(event, 'tab4')">Uluslararası Dergilerde Yayınlanmış Makaleler</button>
                        </div>

                        <div id="tab1" class="tabcontent text-justify">
                            <h3>Ulusal Bilimsel Toplantılarda Sunulan Bildiriler</h3>
                            <p> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2"> 1) </dt><dd class="col-sm-9 col-9 "> Göyenç, Y., M. Orhan, İ. Karadede, ve F.A. Başçiftçi, “Bolton Uyumsuzluğu Olmayan Bireylerde Moyers Tablosu Değerlerinin İncelenmesi,” 5. Uluslar arası Türk Ortodonti Derneği Kongresi, Antalya, Türkiye, Bildiri Kitapçığı, s:78, 1996.</dd></div>
                            <div class="row mt-4 mt-lg-4"> <dt class="col-lg-2 text-right col-2">2) </dt><dd class="col-sm-9 col-9"> Sarı, Z., Y. Göyenç, A. Karaman, ve F.A. Başçiftçi, “Angle Klas II Bölüm 1 Maloklüzyonlu Bireylerde Hareketli Plaklarla Birlikte Jasper Jumper Uygulaması-Olgu Sunumu,” 5. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Ankara, Türkiye, Bildiri Kitapçığı, s:48, 1997</dd></div>
                            <div class="row mt-4 mt-lg-4"> <dt class="col-lg-2 text-right col-2"> 3) </dt><dd class="col-sm-9 col-9"> Güler, N., S. Uçkan, M. Orhan, M. Gürol, F.A. Başçiftçi, ve P. Yatmaz, “Sementifying Fibroma ve Retrognatili Bir Olguya Kombine Tedavi Yaklaşımı,” Türk Oral ve Maksillofasiyal Cerrahi Derneği 6. Uluslar Arası Bilimsel Kongresi, Antalya, Türkiye, 1998.</dd></div>
                            <div class="row mt-4 mt-lg-4">  <dt class="col-lg-2 text-right col-2">4) </dt><dd class="col-sm-9 col-9"> Karaman, A.İ., İ.E. Gelgör, ve F.A. Başçiftçi, “Rapid Maksiller Ekspansiyon Sonrası Yumuşak Doku Değişikliklerinin İncelenmesi,” 7. Uluslar arası Türk Ortodonti Derneği Kongresi, İstanbul, Türkiye, Bildiri Kitapçığı, s:99, 2000</dd></div>
                            <div class="row mt-4 mt-lg-4">  <dt class="col-lg-2 text-right col-2"> 5) </dt><dd class="col-sm-9 col-9"> Orhan, M., F.A. Başçiftçi, S. Uçkan, ve N. Mutlu, “Erişkin Sınıf II Bölüm 1 Maloklüzyonlu Olguda Anterior Segmental Osteotomi Uygulaması,” 7. Uluslar arası Türk Ortodonti Derneği Kongresi, İstanbul, Türkiye, Bildiri Kitapçığı, s:124, 2000</dd></div>
                            <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 6)  </dt><dd class="col-sm-9 col-9">Orhan, M., F.A. Başçiftçi, ve S. Malkoç, “Mandibuler Keser Eksikliği ya da Çekimi Durumunda Tedavi Yaklaşımı (İki Olgu Sunumu),” Selçuk Üniv. Dişhek. Fak 3. Uluslararası Sempozyumu, Ürgüp, Türkiye, Bildiri Kitapçığı, s:45, 2000</dd></div>
                            <div class="row mt-4 mt-lg-4">  <dt class="col-lg-2 text-right col-2"> 7) </dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., A.İ. Karaman, ve A. Demir, “Anormal Yutkunma Fonksiyonunda Alışkanlık Kırıcı Apareylerin Uygulanması-İki Olgu Sunumu,” Selçuk Üniv. Dişhek. Fak 3. Uluslararası Sempozyumu, Ürgüp, Türkiye, Bildiri Kitapçığı, s:10, 2000</dd></div>
                            <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 8) </dt><dd class="col-sm-9 col-9"> Demir, A., ve F.A. Başçiftçi, “Transpozisyonlu Dişler ve Ortodontik Tedavisi (Olgu Sunumu),” Selçuk Üniv. Dişhek. Fak 3. Uluslararası Sempozyumu, Ürgüp, Türkiye, Bildiri Kitapçığı, s:11, 2000</dd></div>
                            <div class="row mt-4 mt-lg-4">  <dt class="col-lg-2 text-right col-2"> 9) </dt><dd class="col-sm-9 col-9"> Demir, A., A.İ. Karaman, F.A. Başçiftçi, S. Malkoç, ve İ.E. Gelgör, “Gömülü Dişlerin Ortodontik Olarak Sürdürülmesinde Yeni Bir Teknik (Olgu Sunumu),” Selçuk Üniv. Dişhek. Fak 3. Uluslararası Sempozyumu, Ürgüp, Türkiye, Bildiri Kitapçığı, s:12, 2000</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 10) </dt><dd class="col-sm-9 col-9"> Sarı, Z., F.A. Başçiftçi, S. Malkoç, ve T. Uysal, “Farklı Sefalometrik Çizim Tekniklerinin Karşılaştırılması,” 7. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Ankara, Bildiri Kitapçığı, s:17, 2001</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 11) </dt><dd class="col-sm-9 col-9"> Sarı, Z., F.A. Başçiftçi, T. Uysal, ve A. Büyükerkmen, “Retansiyon Dönemindeki Hastaların Dişlerinin Beyazlatılması,” 7. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Ankara, Bildiri Kitapçığı, s:20, 2001</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 12) </dt><dd class="col-sm-9 col-9"> Şener, Y., F. Kahvecioğlu, ve F.A. Başçiftçi, “Bir Olgu Nedeniyle Füzyon Tedavisi,” Türk Pedodonti derneği 12. ulusal kongresi, Bodrum, Türkiye, Bildiri Kitapçığı, s:20, 2001</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 13) </dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, İ.E. Gelgör, ve M. Nur, “Molar Distalizasyonunda Modifiye Distal Jet Apareyi(Vaka Raporu),” 7. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Ankara, Bildiri Kitapçığı, s:36, 2001</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 14) </dt><dd class="col-sm-9 col-9"> Sarı, Z., T. Uysal, ve F.A. Başçiftçi, “Rapid Palatal Ekspansiyon Uygulamalarında Erken Dönemde Görülen Relapsın Belirlenmesi,” Selçuk Üniv. Dişhek. Fak. 1. Uluslararası Kongresi, Konya, Türkiye, Bildiri Kitapçığı, s:87, 2002</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 15) </dt><dd class="col-sm-9 col-9"> Uysal, T., F.A. Başçiftçi, Z. Sarı, ve A. Büyükerkmen, “Beyazlatmadan Önce ve Sonra Uygulanan Asitlemenin Ortodontik Braketlerin Bağlanma Dayanımına Etkisi,” Selçuk Üniv. Dişhek. Fak. 1. Uluslararası Kongresi, Konya, Türkiye, Bildiri Kitapçığı, s:84, 2002</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 16) </dt><dd class="col-sm-9 col-9"> Sarı, Z., T. Uysal, A.İ. Karaman, S. Üşümez, F.A. Başçiftçi, ve A. Demir, “Ortodontik Maloklüzyonlar ve Tedavi Seçeneklerinin Değerlendirilmesi: Epidemiyolojik Çalışma,” Selçuk Üniv. Dişhek. Fak. 1. Uluslararası Kongresi, Konya, Türkiye, Bildiri Kitapçığı, s:83, 2002</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 17) </dt><dd class="col-sm-9 col-9"> Sarı, Z., B. Çatalbaş, A. Demir, T. Uysal, S. Üşümez, ve F.A. Başçiftçi, “Sınıf II Divizyon 2 Maloklüzyona Sahip Bireylerde Hyoid Kemik Pozisyonu,” Selçuk Üniv. Dişhek. Fak. 1. Uluslararası Kongresi, Konya, Türkiye, Bildiri Kitapçığı, s:81, 2002</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 18) </dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., H. İşeri, ve S. Uçkan, “Sınıf III Asimetrilerde Ortodontik ve Ortognatik Cerrahi Tedavisi (Vaka Raporu),” Selçuk Üniv. Dişhek. Fak 1. Uluslararası Kongresi, Konya, Türkiye, Bildiri Kitapçığı, s:101, 2002</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 19) </dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., A. Büyükerkmen, T. Uysal, ve A. Demir, “Çekimli Ortodontik Tedavilerin Holdaway Yumuşak Doku Analizi ile Değerlendirilmesi,” 8. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Konya, Bildiri Kitapçığı, s:32, 2003</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 20) </dt><dd class="col-sm-9 col-9"> Demir, A., T. Uysal, E. Güray, ve F.A. Başçiftçi, “Oklüzal Faktörler ve Çiğneme Kas Hassasiyeti Arasındaki İlişki,” 8. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Konya, Bildiri Kitapçığı, s:32, 2003</dd></div>
                            <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2">  21) </dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., H. İşeri, S. Malkoç, ve H.H. Korkmaz, “Mandibular Ortahat Distraksiyon Osteogenesisinin Biomekanik Etkilerinin Sonlu Elemanlar Yöntemi (FEM) ile Değerlendirilmesi,” 8. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Konya, Bildiri Kitapçığı, s:24, 2003</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 22) </dt><dd class="col-sm-9 col-9"> Üşümez, S., T. Uysal, Z. Sarı, F.A. Başçiftçi, A.İ. Karaman, ve E. Güray, “Sınıf II,1 Maloklüzyona Sahip Hastalarda Pre-Ortodontik Trainer Apareyinin Etkileri,” 8. Uluslar arası Türk Ortodonti Derneği Sempozyumu, Konya, Bildiri Kitapçığı, s:28, 2003</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 23) </dt><dd class="col-sm-9 col-9"> Uysal, T., Z. Sarı, B. Memili, ve F.A. Başçiftçi, “Çenelerarası diş boyut uyuşmazlığı ve maloklüzyon. Ne kadar ilişkililer?” 9. Uluslararası Türk Ortodonti Derneği Kongresi, Belek, Bildiri Kitapçığı, s:73, 2004</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 24) </dt><dd class="col-sm-9 col-9"> Nur, M., S. Malkoç, B. Çatalbaş, ve F.A. Başçiftçi, “Farklı maloklüzyon gruplarında çeneler arası diş boyutu uyumsuzlularının karşılaştırılması” Dünden bugüne Türk Dişhekimliği sempozyumu Konya 2005</dd></div>
                           <div class="row mt-4 mt-lg-4">     <dt class="col-lg-2 text-right col-2"> 25) </dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., ve S.İ. Ramoğlu “Asimetrik üst çene genişletmesi: Vaka raporu” 10. Uluslararası Türk Ortodonti Derneği Kongresi, İstanbul, Türkiye, Bildiri Kitapçığı, s:150, 2006</dd></div>
                           <div class="row mt-4 mt-lg-4">     <dt class="col-lg-2 text-right col-2"> 26) </dt><dd class="col-sm-9 col-9"> Memili, B.,ve F.A. Başçiftçi, “Kanin retraksiyonunda hibrit retraktör ve mini vida kullanımı: 2 vaka raporu” 11. Uluslararası Türk Ortodonti Derneği Kongresi, İzmir, Türkiye, Bildiri Kitapçığı, s:197, 2008</dd></div>
                           <div class="row mt-4 mt-lg-4">     <dt class="col-lg-2 text-right col-2"> 27) </dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., Z. İleri, R. Yavuzer, ve M. Akın “İskeletsel sınıf III olgunun ortodontik-cerrahi tedavisi: vaka raporu” 11. Uluslararası Türk Ortodonti Derneği Kongresi, İzmir, Türkiye, Bildiri Kitapçığı, s:185, 2008</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 28) </dt><dd class="col-sm-9 col-9"> İleri, Z., ve F.A. Başçiftçi, “Tek taraflı iskeletsel çapraz kapanış olgularında asimetrik hızlı üst genişletmesinin dentofasiyal yapılar üzerine etkileri” 11. Uluslararası Türk Ortodonti Derneği Sempozyumu, Antakya, Bildiri Kitapçığı, s:23, 2009</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 29) </dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., Z. İleri, M. Akın, ve S. Bayram “Hızlı üstçene genişletmesinde minividalar ile vertikal kontrol: Olgu sunumu” 11. Uluslararası Türk Ortodonti Derneği Sempozyumu, Antakya, Bildiri Kitapçığı, s:59, 2009</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 30) </dt><dd class="col-sm-9 col-9"> İleri, Z., ve F.A. Başçiftçi, “Transversal yetmezlik ve kron-kök açılanması nedeniyle gömük kalmış üst santral dişin tedavisi: Olgu raporu” 11. Uluslararası Türk Ortodonti Derneği Sempozyumu, Antakya, Bildiri Kitapçığı, s:61, 2009</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 31) </dt><dd class="col-sm-9 col-9"> Akın, M., Z.M.Baka, Z.İleri ve F.A. Başçiftçi, “Güncel Self Etch ve Total Etch Adeziv Sistemlerinin Mine ve Dentin Yüzeylerinde Ortodontik Braketlere Bağlanma Dayanımlarının Karşılaştırılması” 12. Uluslararası Türk Ortodonti Derneği Sempozyumu, İzmir, Bildiri Kitapçığı, s:62, 2011</dd></div>
                           <div class="row mt-4 mt-lg-4">     <dt class="col-lg-2 text-right col-2"> 32) </dt><dd class="col-sm-9 col-9"> Bayram, S., F.A. Başçiftçi, Z.İleri ve M. Akın, “Farklı Braket Sistemlerinin Bukkal Koridor Alanı Üzerine Etkisinin Değerlendirilmesi” 12. Uluslararası Türk Ortodonti Derneği Sempozyumu, İzmir, Bildiri Kitapçığı, s:190, 2011</dd></div>
                            <div class="row mt-4 mt-lg-4">    <dt class="col-lg-2 text-right col-2"> 33) </dt><dd class="col-sm-9 col-9"> İleri, Z., ve F.A. Başçiftçi, “Hasta Kooperasyonunun Ortodontik Tedavi Üzerine Etkisi” 12. Uluslararası Türk Ortodonti Derneği Sempozyumu, İzmir, Bildiri Kitapçığı, s:189, 2011</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 34) </dt><dd class="col-sm-9 col-9"> Akın, M., Z.İleri, Ö.Polat, ve F.A. Başçiftçi, “Sınıf II subdivizyon malokluzyonunda mandibular asimetrinin derecesi” 13. Uluslararası Türk Ortodonti Derneği Sempozyumu, Antalya, Bildiri Kitapçığı, s:124, 2012</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 35) </dt><dd class="col-sm-9 col-9"> İleri, Z., M. Osman ve F.A. Başçiftçi, “Aşırı dar maksiller ve mandibular dental arkların self-ligating sistemlerle düzeltimi” 13. Uluslararası Türk Ortodonti Derneği Sempozyumu, İstanbul, Bildiri Kitapçığı, s:263, 2013</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 36) </dt><dd class="col-sm-9 col-9"> Polat, Ö., Z. İleri, F.A. Başçiftçi, ve D. Dolanmaz, “Aşrı iskeletsel sınıf III olgunun ortodontik tedavi ile kombine çift çene ortognatik cerrahisi” 13. Uluslararası Türk Ortodonti Derneği Sempozyumu, İstanbul, Bildiri Kitapçığı, s:259, 2013</dd></div>
                             <div class="row mt-4 mt-lg-4">   <dt class="col-lg-2 text-right col-2"> 37) </dt><dd class="col-sm-9 col-9"> Akın, M., Y.E. Akgül, Z. İleri ve F.A. Başçiftçi, “Hibrit genişletme apareyinin üç boyutlu değerlendirilmesi: Pilot çalışma” 13. Uluslararası Türk Ortodonti Derneği Sempozyumu, İstanbul, Bildiri Kitapçığı, s:34, 2013</dd></div>
                            </p>
                            </div>
                        </div>

                        <div id="tab2" class="tabcontent">
                            <h3>Ulusal Dergilerde Yayınlanmış Makaleler</h3>
                            <p><div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">1)</dt><dd class="col-sm-9 col-9"> Alptekin, N.Ö., U.S. Uçan, H. Solmaz, O. Erganiş, E.O. Erdemir, ve F.A. Başçiftçi, “Ortodontik Tedavinin Dişeti Sağlığına Etkisi:Klinik ve Mikrobiyolojik Gözlemler”, Ankara Üniv. Dişhek. Fak. Derg, 26, 167-178 (1999).</dd></div>
                               <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2"> 2)</dt><dd class="col-sm-9 col-9"> Alptekin, N.Ö., F. Kurtoğlu, U.S. Uçan, O. Erganiş, B. Serpek, E.O. Erdemir, ve F.A. Başçiftçi, “Ortodontik Aparey Kullanan Bireylerde Subgingival Mikrobiyal Flora ile Dişeti Oluğu Sıvısı Alkalen Fosfataz ve Aspartat Aminotransferaz Enzim Aktiviteleri Arasındaki İlişki", Selçuk Üniv. Dişhek. Fak. Derg, 9, 59-63 (1999).</dd></div>
                               <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2"> 3) </dt><dd class="col-sm-9 col-9">Başçiftçi, F.A., M. Orhan, ve S. Malkoç, “Tek Alt Keser Çekimi ya da Eksikliği Durumunda Tedavi Sonundaki Anterior Oklüzal İlişkinin Tahmini ve Değerlendirilmesi”, Selçuk Üniv. Dişhek. Fak. Derg, 10, 108-112 (2000).</dd></div>
                               <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2"> 4) </dt><dd class="col-sm-9 col-9">Karaman, A.İ., S. Malkoç, F.A. Başçiftçi, ve N. Mutlu, “Normal ve Cerrahi Destekli Rapid Maksiller Ekspansiyon Uygulamaları”, Türk Ortodonti Dergisi, 14, 81-88 (2001)</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  5)</dt><dd class="col-sm-9 col-9"> Üşümez, S., ve F.A. Başçiftçi, “Sınıf II, Bölüm 2 Maloklüzyonlarda Sabit Tedavi ile Meydena Gelen Değişikliklerin İncelenmesi”, Türk Ortodonti Dergisi, 14, 125-131 (2001).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  6)</dt><dd class="col-sm-9 col-9"> Başçiftçi F.A., M. Orhan, S. Uçkan, ve S. Üşümez, “İskeletsel Sınıf III Olgularda Ortodontik-Cerrahi Yaklaşımlar (iki Vaka Raporu)”, T. Klin. Dişhek. Bil, 7, 138-144 (2001).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  7) </dt><dd class="col-sm-9 col-9">Şener, Y., F. Kahvecioğlu, ve F.A. Başçiftçi, “Füzyon (Bir Olgu Sunumu)” Selçuk Üniv. Dişhek. Fak. Derg. 11, 86-89 (2001).</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   8) </dt><dd class="col-sm-9 col-9">Başçiftçi, F.A., A. Demir, Z. Sarı, ve T. Uysal, “Konya Yöresi Okul Çocuklarında Ortodontik Maloklüzyonların Prevelansının Araştırılması: Epidemiyolojik Çalışma”, Türk Ortodonti Dergisi, 15, 92-98 (2002).</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   9) </dt><dd class="col-sm-9 col-9">Sarı, Z., F.A. Başçiftçi, T. Uysal, ve S. Malkoç S. “Üç Farklı Sefalometrik Çizim Yönteminde Araştırıcılar ve Tekniklerin Karşılaştırılması”, Türk Ortodonti Dergisi, 15, 99-107 (2002).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  10)</dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, ve İ.E. Gelgör, “Ortodontik Tedavi Gören Hastalarda Headgear ve Ağız İçi Elastik Kullanımının Hasta kooperasyonu Üzerine Etkisi”, Türk Ortodonti Dergisi, 15, 108-115 (2002).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  11)</dt><dd class="col-sm-9 col-9"> Uysal, T., F.A. Başçiftçi, Z. Sarı, ve A. Büyükerkmen, “Beyazlatmadan Önce ve Sonra Uygulanan Asitlemenin, Ortodontik Braketlerin Bağlanma Kuvvetine Etkisi”, Türk Ortodonti Dergisi, 15, 116-121 (2002).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  12)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., T, Uysal, A. Büyükerkmen, ve Z. Sarı, “Retansiyon Dönemindeki Hastalarda Vital Beyazlatma Tekniğinin Etkinliği”, Türk Ortodonti Dergisi, 15, 122-130 (2002).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  13) </dt><dd class="col-sm-9 col-9">Başçiftçi, F.A., İ.E. Gelgör, S. Malkoç, ve Z. Sarı, “İkizlerde Ortodontik Tedavi Yaklaşımı (Vaka Raporu)” Selçuk Üniv. Dişhek. Fak. Derg. 12, 6-11 (2002)</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  14)</dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, ve S. Malkoç, “Fonksiyonel Sınıf III Olgularda Plaklı Jasper Jumper Apareyinin Etkileri (İki Vaka Raporu)”, Türk Ortodonti Dergisi, 15, 183-192 (2002)</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  15)</dt><dd class="col-sm-9 col-9"> Sarı, Z., T. Uysal, B. Çatalbaş, A. Demir, S. Üşümez, ve F.A. Başçiftçi, “Sınıf I ve Sınıf II Divizyon 2 Maloklüzyona Sahip Bireylerde Hyoid Kemik Pozisyonu”, Türk Ortodonti Dergisi, 16, 95-101 (2003).</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   16)</dt><dd class="col-sm-9 col-9"> Sarı, Z., T. Uysal, ve F.A. Başçiftçi, “Rapid Palatal Ekspansiyon Uygulamalarında Erken Dönemde Görülen Relapsın Belirlenmesi”, Türk Ortodonti Dergisi, 16,113-118 (2003).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  17)</dt><dd class="col-sm-9 col-9"> Sarı, Z., T. Uysal, A.İ. Karaman, F.A. Başçiftçi, S. Üşümez, ve A. Demir, “Ortodontik Maloklüzyonlar ve Tedavi Seçeneklerinin Değerlendirilmesi”, Türk Ortodonti Dergisi, 16, 119-126 (2003).</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  18)</dt><dd class="col-sm-9 col-9"> Uysal, T., Z. Sarı, Y. Şukurıca, F.A. Başçiftçi, ve B. Çatalbaş, ‘Sınıf II Bölüm 1 Mandibuler Retrognati Vakalarında Uygulanan Kompenzasyon Tedavilerinin Yumuşak Dokular Üzerine Etkilerinin İncelenmesi’, Türk Ortodonti Dergisi, 17, 173-182 (2004)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   19)</dt><dd class="col-sm-9 col-9"> Yıldırım, S., T. Uysal, ve F.A. Başçiftçi, ‘Antibakteriyel Özelliğe Sahip Self Etchinh Adeziv Sistemin Dekalsifikasyon Sonrasında Bağlanma Dayanımı Üzerine Etkileri’, Türk Ortodonti Dergisi, 17, 194-199 (2004)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   20)</dt><dd class="col-sm-9 col-9"> Nur, M., S. Malkoç, B. Çatalbaş, F.A. Başçiftçi, ve A. Demir, “Farklı Malokluzyon Gruplarında Çeneler Arası Diş Boyutu Uyumsuzluklarının Karşılaştırılması” Türk Ortodonti Dergisi, 18, 99-108 (2005)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   21)</dt><dd class="col-sm-9 col-9"> Demir, A., T. Uysal, ve F.A. Başçiftçi, “Sınıf II Malokluzyonun İskeletsel Ve Dental Karakteristiğinin Belirlenmesi” Türk Ortodonti Dergisi, 18 205-214 (2005)</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  22)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., S. Üşümez, S. Malkoç, ve M. Orhan, “Farklı Braket Taban Özelliklerinin Tutuculuğa Etkisinin İncelenmesi” Türk Ortodonti Dergisi, 19, 141-150 (2006)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   23)</dt><dd class="col-sm-9 col-9"> Memili, B., ve F.A. Başçiftçi, “Çekimli Vakalarda Mikrovida Yöntemi İle Üst Kanin Distalizasyonunun Ankraj Yönünden Değerlendirilmesi” SÜ Dişhek Fak Derg, 18, 161-169 (2009)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    24)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., G. Bişirici, ve D. Dolanmaz, “Application of floating bone principle in a class II div 1 case treated by distraction osteogenesis” SÜ Dişhek Fak Derg, 18, 311-315 (2009)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    25)</dt><dd class="col-sm-9 col-9"> Demir, A., F.A. Başçiftçi, S.Üşümez ve Y,Göyenç,“Sınıf II Malokluzyonun İki Aşamalı Tedavisinin Uzun Süreli Sonuçları” Türk Ortodonti Dergisi, 23, 256-267 (2010)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    26)</dt><dd class="col-sm-9 col-9"> İleri, Z., ve F.A. Başçiftçi, “Gerçek Tek Taraflı Posterior Çapraz Kapanış Olgularında Asimetrik Hızlı Üst Çene Genişletmesi Sonucunda Oluşan Dental ve Alveolar Devrilme” Türk Ortodonti Dergisi, 23, 226-240 (2010)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    27)</dt><dd class="col-sm-9 col-9"> İleri, Z., ve F.A. Başçiftçi, “Tek Taraflı İskeletsel Çapraz Kapanış Olgularında Yapılan Asimetrik RME’nin Çenelerin Yatay Yön Boyutlarına Etkileri” SÜ Dişhek Fak Derg, 19, 189-196 (2010)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    28)</dt><dd class="col-sm-9 col-9"> İleri, Z., ve F.A. Başçiftçi, “Effects of Asymmetric Rapid Maxillary Expansion on Mandibular Condyle Position” SÜ Dişhek Fak Derg, 19, 204-213 (2010)</dd></div>
                           <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     29)</dt><dd class="col-sm-9 col-9"> Aksakallı, S., M. Akın, A.Demir, ve F.A. Başçiftçi, “The effect of tooth bleaching on the shear bond strength of orthodontic brackets using total-etching primer systems” SÜ Dişhek Fak Derg, 20,98-102 (2011)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    30)</dt><dd class="col-sm-9 col-9"> Baka, Z.M., M. Akın, Z. İleri, ve F.A. Başçiftçi, “Güncel self-etch ve total-etch adeziv sistemlerinin dentin yüzeyinde ortodontik braketlere bağlanma dayanımlarının karşılaştırılması” SÜ Dişhek Fak Derg, 20,145-151 (2011)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    31)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., Z, Ileri ve R, Yavuzer, “İskeletsel Sınıf III Açık Kapanışa Sahip Olgunun Ortodontik-Cerrahi Tedavisi” Selçuk Tıp Derg 28, 50-53 (2012)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   32)</dt><dd class="col-sm-9 col-9"> Akın M., F.A. Başçiftçi, “Ortodontide invisaling tekniği” SÜ Dişhek Fak Derg, 22,54-59 (2013)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   33)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., Z.M. Baka ve M.Akın, “Kapaklı braketlerle yapılan ortodontik tedaviler sonucu elde edilen klinik sonuçlar” Türkiye Klinikleri J Dent Sci-special topics 4, 26-34 (2013)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    34)</dt><dd class="col-sm-9 col-9"> Akin M., E.Dilber, F.A.Basciftci, ve B.Ozturk“Effect of microabrasion on teeth color” Turkish J Orthod 26,80-84 (2013)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    35)</dt><dd class="col-sm-9 col-9"> Akin M., M.Tezcan, Z.İleri, ve F.A.Basciftci, “Incidence of white spot lesion during fixed orthodontic treatment” Turkish J Orthod 26,98-102 (2013)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    36)</dt><dd class="col-sm-9 col-9"> Bayram, S., F.A.Basciftci, ve E. Kurar, “Mandibular Prognathism and Genetic Transmission in Turkish Families” Turkish J Orthod 26,114-118 (2013)</dd></div>
                           <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     37)</dt><dd class="col-sm-9 col-9"> Akın, M.,  Z. İleri, S. Aksakallı ve F.A. Başçiftçi “Mechanical Properties of Different Aesthetic Archwires” Turkish J Orthod 27,85-89 (2014)</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  38)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., Z.M. Baka, S. Bayram and E.A. Erdur “3-Year Follow-Up of Nonextraction Crowded Cases Treated With the Damon System” Turkish J Orthod 27,39-45 (2014)</dd></div>
                              <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  39)</dt><dd class="col-sm-9 col-9"> Akın,M., O.Polat, Z.İleri and F.A.Basciftci“Effects of the Activator and Twin Block on Facial Soft Tissue Thickness in Class II Division 1 Patients” Turkish J Orthod 27,128-135 (2014)</dd></div>
                            <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    40) </dt><dd class="col-sm-9 col-9">Akın, M., Z. İleri,  Ö. Polat, ve F.A. Başçiftçi “Evaluation of mandibular asymmetry in class II subdivision malocclusion” Selcuk Dental Journal, 2: 43-50 (2015)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   41)</dt><dd class="col-sm-9 col-9"> İleri, Z., Z.M.Baka, M.Osman, F.İ.Uçar ve F.A. Başçiftçi, “Primer cerrahi öncesi erken maksiller ortopedi ile tedavi edilmiş tek taraflı dudak ve damak yarıklı adolesanlarda orta yüz eksikliğinin değerlendirilmesi” Türkiye Klinikleri J Dental Sci 22(3),169-177 (2016)</dd></div>
                             <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   42)</dt><dd class="col-sm-9 col-9"> Z.M.,  Baka, Erdur, E.A., Alp, S., ve F.A. Başçiftçi “Unilateral dudak damak yarığına sahip hastalarda farengeal havayolunun değerlendirilmesi” Selcuk Dental Journal, 4: 170-177 (2017)</dd></div>
                            </p>
                        </div>

                        <div id="tab3" class="tabcontent">
                            <h3>Uluslararası Bilimsel Toplantılarda Sunulan Bildiriler</h3>
                            <p><div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2"> 1)</dt><dd class="col-sm-9 col-9"> Orhan, M., F.A. Başçiftçi, S. Uçkan, N. Mutlu, ve S. Üşümez, “Class III Malocclusion and Orthognatic Surgery: Two Case Reports,” Proc. Second Bi-National Conference on Oral and Maxillofacial Surgery, Tel-Aviv, Abst# 61, Israel, 1999
                                </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  2)</dt><dd class="col-sm-9 col-9"> Sarı, Z., Y. Göyenç, S. Üşümez, ve F.A. Başçiftçi, “The Effects of Jasper Jumper İncorporated to Removable Plates on Dentofacial Structures in İndividuals with Angle Class II Division 1 Malocclusion,” Proc. Second Bi-National Conference on Oral and Maxillofacial Surgery, Tel-Aviv, Abst# 62, Israel, 1999
                                </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2"> 3)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., S. Usumez, ve Z. Sarı, “Hemisection: an Alternative Approach in The Treatment of Second Premolar Agenesis:Report of a Case,” Proc. Second Bi-National Conference on Oral and Maxillofacial Surgery, Tel-Aviv, Abst# 63, Israel, 1999
                            </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  4)</dt><dd class="col-sm-9 col-9"> Uçkan, S., N. Mutlu, A.İ. Karaman, S. Malkoç, ve F.A. Başçiftçi, “Rapid Maxillary Expansion with and Without Surgery,” Proc. 5th Congress of the Balkan Stomatological Society, Abst# 34, Thessaloniki, 2000
                            </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  5)</dt><dd class="col-sm-9 col-9"> Üşümez, S., H. İşeri, M. Orhan, ve F.A. Başçiftçi, “Effect of Maxillary Expansion on Nocturnal Enuresis,” Proc. 76th Congress of the European Orthodontic Society, Creete, Abst# 304, Greece, 2000
                            </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  6)</dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, ve S. Malkoç, “The Application of a Splinted Jasper Jumper Appliance in Functional Class III Subjects- Two Case Reports,” Proc. 76th 5Congress of the European Orthodontic Society,  Creete, Abst# 147, Greece, 2000
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   7)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., N. Mutlu, A.İ. Karaman, S. Malkoç, ve H. Küçükkolbaşı, “The effect of RME on Nasal Airway Resistance,” Proc.6th Congress of the Balkan Stomatological Society, Bucharest, Abst# 67, Romania, 2001.
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   8)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., ve A.İ. Karaman, “The Effect of Modified Acrylic Bonded Rapid Maxillary expansion Appliance and Vertical Chin Cup on Dentofacial Structures,” Proc. 77th Congress of the European Orthodontic Society, Ghent, Abst# 97, Belgium, 2001
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   9)</dt><dd class="col-sm-9 col-9"> Malkoç, S., F.A. Başçiftçi, ve İ.E. Gelgör, “Different Treatment Methods in İdentical Twins: Two Cases Reports,” Proc 6th Congress of the Balkan Stomatological Society, Bucharest, Abst# 168, Romania, 2001
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   10)</dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, ve Ö. Polat, “The Effects of an İmplant Supported Modified Distal Jet Appliance on Dentofacial Structures- A Case Report,” Proc. 77th Congress of the European Orthodontic Societ,  Ghent, Abst# 209, Begium, 2001.
                             </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   11)</dt><dd class="col-sm-9 col-9"> Demir, A., F.A. Başçiftçi, ve T. Uysal, “Prevelance of Dental Anomalies in School Children: An Epidemiologic Study,” Proc. 7th Congress of the Balkan Stomatological Society, Kuşadası, Abst# 54, Turkey, 2002.
                             </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   12)</dt><dd class="col-sm- col-9"> Başçiftçi, F.A., Z. Sarı, T. Uysal, ve A. Büyükerkmen, “The Effects of Activator Treatment on the Craniofacial Structures of Class II Division 1 Patients,” Proc. 7th Congress of the Balkan Stomatological Society, Kuşadası, Abst# 55, Turkey, 2002.
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   13)</dt><dd class="col-sm-9 col-9"> Başçiftçi, FA., S. Üşümez, Z. Sarı, T. Uysal, ve A. Büyükerkmen, “Bond Strengths of Orthodontic Brackets to Bleached Enamel Surfaces Compared with Sandblasting and Acid Etching”, Proc. 7th Congress of the Balkan Stomatological Society, Kuşadası, Abst# OP047, 50, Turkey, 2002.
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   14)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., A. Büyükerkmen, T. Uysal, ve S. Üşümez, “Determination of Holdaway Soft Tissue Norms in Turkish Adults,” Proc. 7th Congress of the Balkan Stomatological Society, Kuşadası, Abst# 51, Turkey, 2002
                            </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">  15)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., ve S. Üşümez, “A Comparative Study of Extraction and Non-Extraction Treatment on Dentofacial Structures,” Proc. 78th Congress of the European Orthodontic Society, Sorrento, Abst# 284, Italy, 2002.
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   16)</dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, ve İ.E. Gelgör, “Effects of Headgear, İntraoral Elastic Wear and Patient Compliance During Orthodontic Treatment,” Proc. 78th Congress of the European Orthodontic Society, Sorrento, Abst# 366, Italy, 2002
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   17)</dt><dd class="col-sm-9 col-9"> Üşümez, S., ve F.A. Başçiftçi, “Skeletal and Dental Changes Associated with Extraction or Non-Extraction Treatment of Class II Division 2 Malocclusions,” Proc. 78th Congress of the European Orthodontic Society, Sorrento, Abst# 145, Italy, 2002
                             </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   18)</dt><dd class="col-sm-9 col-9"> Başçiftçi, F.A., H. İşeri, ve S. Uçkan, “Intraoral Distraction Osteogenesis in a Facial Asymmetry Case,” Proc. 78th Congress of the European Orthodontic Society, Sorrento, Abst# 113, Italy, 2002
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   19)</dt><dd class="col-sm-9 col-9"> Üşümez, S., F.A. Başçiftçi, ve S. Malkoç, “The Effect of Bracket Base Desing on Shear Bond Strength,” Proc. 79th Congress of the European Orthodontic Society, Prague, Abst# 374, The Czech Republic, 2003
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   20)</dt><dd class="col-sm-9 col-9"> Uysal, T., A. Demir, F.A. Basciftci ve E. Guray, “Is there a relationship between bruxism and masticotary muscle tenderness among ten to 19 year old Turkish children?” Proc. 9th Congress of the Balkan Stomatological Society, Ohrid, Macedonia 2004
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   21)</dt><dd class="col-sm-9 col-9"> Uysal, T., A. Demir, Z. Sarı, F.A. Basciftci ve A. Büyükerkmen, “Effects of camouflage treatments on dentofacial structures in class II, 1 patients” Proc. 9th Congress of the Balkan Stomatological Society, Ohrid, Macedonia 2004
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   22)</dt><dd class="col-sm-9 col-9"> Demir, A., T. Uysal, F.A. Basciftci ve E. Guray, “The relationship between bruxism and occlusal factors among 7-19 year old Turkish children” Proc. 9th Congress of the Balkan Stomatological Society, Ohrid, Macedonia 2004
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   23)</dt><dd class="col-sm-9 col-9"> Buyukerkmen, A., F.A. Basciftci, ve T.Uysal, “The assesment of cephalometric norms of anatolian turkish adult with normal occlusions and well-balanced faces” Proc. 81sh Congress of the European Orthodontic Society, Amsterdam, The Netherlands 2005
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    24) </dt><dd class="col-sm-9 col-9">Basciftci, F.A., H.H. Korkmaz, ve S. Usumez, “Biomechanical evaluations of chin cup treatment with different forces” Proc. 81sh Congress of the European Orthodontic Society, Amsterdam, The Netherlands 2005
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    25)</dt><dd class="col-sm-9 col-9"> Bisirici, G., F.A. Basciftci, ve H.H. Korkmaz, “Biomechanical evaluations of different miniplates in fixation of fractured human mandible” Proc. 81sh Congress of the European Orthodontic Society, Amsterdam, The Netherlands 2005
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    26)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., T. Uysal, ve Z.Sarı, “Occlusal contacs of different retention procedures and untreated controls in one-year follow up period” Proc. 81sh Congress of the European Orthodontic Society, Amsterdam, The Netherlands 2005
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    27)</dt><dd class="col-sm-9 col-9"> Ramoglu, I., T. Uysal, ve F.A. Basciftci, “Chronologic age, cervical vertebrae and hand-wrist skeletal maturations. Is there a relation?” Proc. 81sh Congress of the European Orthodontic Society, Amsterdam, The Netherlands 2005
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    28)</dt><dd class="col-sm-9 col-9"> Demir, A., Y. Sener, ve F.A. Basciftci, “The comparison of bond strength of two ortho-composite with or without orthodontic button” Proc. 81sh Congress of the European Orthodontic Society, Amsterdam, The Netherlands 2005
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    29)</dt><dd class="col-sm-9 col-9"> Soğancı, E., ve F.A. Basciftci, “Pendred Syndrome- A case report” Proc. 82nd Congress of the European Orthodontic Society, Vienna, Austria 2006
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    30)</dt><dd class="col-sm-9 col-9"> Gürel, H., A. Demir, ve F.A. Basciftci, “Comparison of two bonding approaches in tems of bond strength” Proc. 82nd Congress of the European Orthodontic Society, Vienna, Austria 2006
                           </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     31)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., T. Uysal, ve Y. Goyenc, “New regression equations for mixed dentition arch analysis” Proc. 83rd Congress of the European Orthodontic Society, Berlin, 2007
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    32)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., G. Bisirici, ve D. Dolanmaz, “Application of floating bone principle in a class II div 1 case treated by distraction osteogenesis” Proc 12th Congress of the Balkan Stomatological Society, İstanbul, Türkiye, 2007
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    33)</dt><dd class="col-sm-9 col-9"> Bisirici, G., ve F.A. Basciftci, “Hypersensitive reactions in orthodontic treatments a review of the literature” Proc 12th Congress of the Balkan Stomatological Society, İstanbul, Türkiye, 2007
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    34)</dt><dd class="col-sm-9 col-9"> Malkoc, S., S.I. Ramoglu ve F.A. Basciftci, “Effects of lower incisor extraction on anterior occlusal relationships” Proc. 83rd Congress of the European Orthodontic Society, Berlin, Germany 2007
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    35)</dt><dd class="col-sm-9 col-9"> Canbuldu, N., S. Malkoc, F.A. Basciftci, ve S.I. Ramoglu, “Bolton proportion changes in mandibular incisor extraction patients” Proc. 83rd Congress of the European Orthodontic Society, Berlin, Germany 2007
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    36)</dt><dd class="col-sm-9 col-9"> Gürel, H.G., ve F.A. Basciftci, “Investigation of bacteremia after rapid maxillary expansion” Proc. 83rd Congress of the European Orthodontic Society, Berlin, Germany 2007
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    37)</dt><dd class="col-sm-9 col-9"> Usumez, S., F.A. Basciftci, A. Demir, ve Y. Goyenc, “Is two-phase class II treatment stable in the long term?” Proc. 84th Congress of the European Orthodontic Society, Lisbon, 2008
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    38)</dt><dd class="col-sm-9 col-9"> Memili, B., ve F.A. Basciftci, “The use of hybrid retractor and miniscrew in canine retraction: 2 case reports” Proc. 84th Congress of the European Orthodontic Society, Lisbon, Portugal 2008
                          </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     39)</dt><dd class="col-sm-9 col-9"> Bisirici, G., F.A. Basciftci, ve M.E. Uygun, “Hypersensitive reactions during orthodontic treatment: A review of the literature” Proc. 84th Congress of the European Orthodontic Society, Lisbon, Portugal 2008
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   40)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., ve G. Bisirici, “Finite element method application in orthodontics: A review of the literature” Proc. 84th Congress of the European Orthodontic Society, Lisbon, Portugal 2008
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   41)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., S. Malkoc, B. Çatalbaş, ve M. Nur, “Mesiodistal crown size among different malocclusion” Proc. 84th Congress of the European Orthodontic Society, Lisbon, Portugal 2008
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   42)</dt><dd class="col-sm-9 col-9"> Ileri, Z., S. Malkoç, S.I. Ramoğlu, ve F.A. Başçiftçi, “Effects of lower incisor extraction on anterior occlusion” ” Proc. 14th Congress of the Balkan Stomatological Society, Varva, Bulgaria 2009
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   43)</dt><dd class="col-sm-9 col-9"> Bisirici, G., ve F.A. Basciftci, “Finite element stress analysis of maxillary en masse retraction” Proc. 85th Congress of the European Orthodontic Society, Helsinki, Finland 2009
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   44)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., S. Bayram, Z. İleri, ve M. Akın, “Vertikal control with miniscrews during rapid maxillary expansion: Case Report” Proc 15th Congress of the Balkan Stomatological Society, Thessaloniki, Greece, 2010
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   45)</dt><dd class="col-sm-9 col-9"> Akın, M., F.A.,Basciftci, ve Z. İleri, “Management of white spot lesions by microabrasion methods” Proc 15th Congress of the Balkan Stomatological Society, Thessaloniki, Greece, 2010
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   46)</dt><dd class="col-sm-9 col-9"> Akın, M., E.Dilber, F.A.Basciftci, ve B.Ozturk, “Effects of Microabrasion on Colour of in Vivo Central Incisors” Proc 89th General Session and Exhibition of the IADR, San Diego, California, USA, 2011
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   47)</dt><dd class="col-sm-9 col-9"> Akın, M., F.A.Basciftci, ve Z.M.Baka, “Evaluation of White Spot Lesions Distributıons After Orthodontic Treantments” Proc 16th Congress of the Balkan Stomatological Society, Bucharest, Romania, 2011
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    48)</dt><dd class="col-sm-9 col-9"> Akın, M., ve F.A.Basciftci, “The Effects of Topical-Fluorides and Casein-Phosphopeptide-Amorphous-Calcium-Phosphate on White Spot Lesions” Proc 16th Congress of the Balkan Stomatological Society, Bucharest, Romania, 2011
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    49)</dt><dd class="col-sm-9 col-9"> Karacam, N., F.A.Basciftci, ve A.Fidancıoğlu, “Eruptıon of Palataly Impacted Maxillary Canine with Miniscrew: Case Report” Proc 16th Congress of the Balkan Stomatological Society, Bucharest, Romania, 2011
                          </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   50)</dt><dd class="col-sm-9 col-9"> Bayram, S., F.A.Basciftci, ve A.Fidancıoğlu, “Interdisciplinary Treatment of 2 Cases with Congenitaly Missing Lateral Incisors” Proc 45th Continental European Division of the International Association for Dental Research (CED- IADR), Budapest, Hungary, 2011
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    51)</dt><dd class="col-sm-9 col-9"> Akın, M., F.A.Basciftci, Z.Tosun, Z.İleri, ve S.Bayram, “Orthodontic and Surgical Treatment of Skeletal Class III and Mandibular Asymmetry with Bilateral Sagital Split Osteotomy: Case Report” Proc. Plastic Surgery Special Joint Meeting, Konya, Turkey, 2011
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   52)</dt><dd class="col-sm-9 col-9"> Akın, M., F.A.Basciftci, ve M.Guzes, “The Effect of Topical Fluorides on White Spot Lesion in Patients After Fixed Orthodontic Treatment” Proc 87th Congress of the Eurepean Orthodontic Society, Istanbul, Turkey, 2011
                          </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   53)</dt><dd class="col-sm-9 col-9"> İleri, Z., F.A.Basciftci, ve M.Guzes, “Condylar Asymmetry in Unilateral Posterior Crossbite Patients ” Proc 45th Continental European Division of the International Association for Dental Research (CED- IADR), Budapest, Hungary, 2011
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   54)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., G.Bisirici, H.H.Korkmaz ve M.Kamanlı, “Finite Element Stress Analysis of Maxillary Anterior EnMasse Retraction ” Proc InternationalSymposium on Advances Applied Mechanics and Modern Information Technology, Baku, Azerbaijan, 2011
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    55)</dt><dd class="col-sm-9 col-9"> Kahraman F.B., O.Polat, M.Guzes,Z.Ileri ve F.A.Basciftci, “Relations between the slope of forehead and various dental arch forms” Proc. 88th Congress of the European Orthodontic Society, Santiago de Compostela, Spain 2012
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    56)</dt><dd class="col-sm-9 col-9"> Celik R.M., Z.Ileri ve F.A.Basciftci, “Preoperative orthopaedic treatment of unilateral incomplete cleft lip and palate- case report” Proc. International craniofacial anomalies congress, Isparta, Turkey 2013
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    57)</dt><dd class="col-sm-9 col-9"> Baka Z.M., F.A.Basciftci, ve U.Aslan, “Effects of two different bracket and ligation types on dental plaque retention and microbial flora” Proc 18th Congress of the Balkan Stomatological Society, Skopje, 2013
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    58)</dt><dd class="col-sm-9 col-9"> Demirtas H.K., M.Akin, Z.İleri ve  F.A.Basciftci, “Shear-bond-strength of orthodontic brackets to aged nano-hibrid composite-resin surfaces using different surface preparation” Proc 18th Congress of the Balkan Stomatological Society, Skopje, 2013
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    59)</dt><dd class="col-sm-9 col-9"> Akin M., Z.M.Baka, Z.İleri ve F.A.Basciftci, “Can demineralized enamel surfaces be bonded safely?” Proc 18th Congress of the Balkan Stomatological Society, Skopje, 2013
                         </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    60)</dt><dd class="col-sm-9 col-9"> Bayram S., ve F.A.Basciftci, “Mandibular prognathism and genetic transition in Turkish families” Proc 18th Congress of the Balkan Stomatological Society, Skopje, 2013
                         </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    61)</dt><dd class="col-sm-9 col-9"> Ileri Z., M.Osman, M Akin ve F.A.Basciftci, “Comparison the outcomes of space opening and closure protocols in patients with missing upper laterals” Proc 18th Congress of the Balkan Stomatological Society, Skopje, 2013
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    62)</dt><dd class="col-sm-9 col-9"> Ileri Z., M Akin, F.A.Basciftci, S.Malkoc ve S.I. Ramoglu, “Comparison of skeletal, dentoalveolar and soft-tissue changes after lower incisor extraction and non-extraction treatments” Proc 18th Congress of the Balkan Stomatological Society, Skopje, 2013
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    63)</dt><dd class="col-sm-9 col-9"> Baka Z.M., A.U. Eldeniz, M.B.Guneser ve F.A.Basciftci, “Antibacterial effects of six orthodontic bonding materials” Proc FDI 2013 Istanbul annual world dental congress, İstanbul, Turkey, 2013
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    64)</dt><dd class="col-sm-9 col-9"> Akgul Y., Z.İleri, M.E.Yılmaz, M.Akin ve F.A.Basciftci, “Palatal molding in patient with high palate: Case report” Proc 46th meeting of the continental European division of the international association for dental research, Florence, Italy, 2013
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    65)</dt><dd class="col-sm-9 col-9"> Akin M., O. Polat, Z.İleri ve  F.A.Basciftci, “Effects of activator and twin block on facial soft tissue thickness in class II-division 1” Proc 18th Congress of the Balkan Stomatological Society, Skopje, 2013
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    66)</dt><dd class="col-sm-9 col-9"> Basciftci F.A., Z.M. Baka S. Bayram, E.A.Erdur “3-year follow-up of nonextraction crowded cases treated with the Damon system” 90th Congress of the European Orthodontic Society, Warsaw, Poland 2014
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    67)</dt><dd class="col-sm-9 col-9"> Bayram S., F.A. Basciftci, E. Kurar, “Evaluation of the relationship between p561t and c422f polymorphsims in growth hormone receptor (ghr) gene and mandibular prognathism” 90th Congress of the European Orthodontic Society, Warsaw, Poland 2014
                          </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   68)</dt><dd class="col-sm-9 col-9"> Akın M., Z.M. Baka, Z. İleri, F.A. Basciftci, “Evaluation of alveolar bone changes after asymmetric rapid maxillary expansion” 90th Congress of the European Orthodontic Society, Warsaw, Poland 2014
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    69)</dt><dd class="col-sm-9 col-9"> Baka Z.M., M. Akın, M.E. Yılmaz, F.A. Basciftci, “Class II treatment by Extraction of maxillary first premolars or forsus fatique resistant device: Softtissue effects in comparison” 90th Congress of the European Orthodontic Society, Warsaw, Poland 2014
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    70)</dt><dd class="col-sm-9 col-9"> Polat Ö., F.İ. Uçar, Z. İleri, Z.M. Baka, F.A. Basciftci, “The effects of face masks to malar region and soft tissue” 90th Congress of the European Orthodontic Society, Warsaw, Poland 2014
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    71)</dt><dd class="col-sm-9 col-9"> Akgül Y.E., F.İ. Uçar, Z.M. Baka, Z. İleri, F.A. Basciftci, “The effects of face mask on permanent canine position” 90th Congress of the European Orthodontic Society, Warsaw, Poland 2014
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    72)</dt><dd class="col-sm-9 col-9"> Baka Z.M., M.Akın, Z.İleri, F.A.Başçiftçi, “Demineralize Mine Yüzeylerine Self Etch Sistemler ile Bondlanan Braketlerin Bağlanma Dayanımına Remineralizasyon Prosedürlerinin Etkisi” 14. Uluslararası Türk Ortodonti Derneği Kongresi, Ankara, 2014
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    73)</dt><dd class="col-sm-9 col-9"> Bayram S., Z. İleri, G. Yıldırım, F.A.Başçiftçi, M.E. Yılmaz, “Distraksiyon Osteogenezisi Kullanarak Alveolar Yarık Tedavisi” 14. Uluslararası Türk Ortodonti Derneği Kongresi, Ankara, 2014
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    74)</dt><dd class="col-sm-9 col-9"> Erdur E.A., F.A. Basciftci,“Comparative Evaluation of Novel Laser Ti:Sapphire-Femtosecond in Ceramic-Surface Roughness” 93rd General Session Exhibition of The IADR Boston, USA, 2015
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    75)</dt><dd class="col-sm-9 col-9"> Erdur E.A., F.A. Basciftci,“Could We Achıeve Better SBS with a Novel Laser; Ti:Sapphire Femtosecond? ” 93rd General Session Exhibition of The IADR Boston, USA, 2015
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    76)</dt><dd class="col-sm-9 col-9"> Erdur E.A., R.M. Celik, A. Vural, F.A.Basciftci “The Orthodontic Treatment of Severe Crowding Patients with Damon System: Case Report” 20th Congress of the Balkan Stomatological Society, Bucharest, Romania 2015
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    77)</dt><dd class="col-sm-9 col-9"> Erdur E.A., A. Vural, F.A.Basciftci “The Orthodontic Treatment of Severe Skeletal Class II Patient” 20th Congress of the Balkan Stomatological Society, Bucharest, Romania 2015
                          </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   78)</dt><dd class="col-sm-9 col-9"> Demirtas H.K.,  M. Erol, F.A.Basciftci “Treatment of Skeletal Class II Malocclusion in Growing Patients with Forsus Fatique Resistant Device” 20th Congress of the Balkan Stomatological Society, Bucharest, Romania 2015
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    79)</dt><dd class="col-sm-9 col-9"> Akın M., E.A.Erdur, O.Ozturk, F.A.Basciftci, “Longitudinal Evaluation of Dental Arch Asymmetry in Class II Subdivision Malocclusion Treated with Asymmetric Forsus Fatique Appliances” 91st Congress of the European Orthodontic Society, Venice, Italy 2015
                          </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   80)</dt><dd class="col-sm-9 col-9"> Altındiş S., E.Toy, F.A.Başçiftçi, “Farklı tipteki hızlı üst çene genişletme apareylerinin yüz yumuşak dokularına olan etkilerinin üç boyutlu yüz görüntüleme yöntemi ile değerlendirilmesi” 14. Uluslararası Türk Ortodonti Derneği Sempozyumu, Eskişehir, 2015
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    81)</dt><dd class="col-sm-9 col-9"> Vural A., M.Erol, M.E.Yılmaz, F.A.Başçiftçi, “Sınıf II subdivizyon ve sınıf III subdivizyon hastalarda mandibular asimetri” 14. Uluslararası Türk Ortodonti Derneği Sempozyumu, Eskişehir, 2015
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    82)</dt><dd class="col-sm-9 col-9"> Yılmaz E., G.Yurttadur, F.A.Başçiftçi, M.Akın, “Sınıf I, Sınıf II ve Sınıf III maloklüzyonlarda üst dudak, alt dudak, total yüz uzunluğu ve nazal projeksiyon açısının değerlendirilmesi” 14. Uluslararası Türk Ortodonti Derneği Sempozyumu, Eskişehir, 2015
                          </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     83)</dt><dd class="col-sm-9 col-9"> Tezcan M., F.A.Başçiftçi, “Evaluation of Salivary Nickel and Chromium Levels in Two Different and Ligation Types” 45th Annual Meeting & Exhibition of AADR Los Angeles, USA, 2016
                         </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    84)</dt><dd class="col-sm-9 col-9"> Erdur E.A., A.Hergüner, F.A.Başçiftçi, M.Akın, Z.İleri, S.Hergüner, “İmpact of orthodontic treatment on quality of life, self-esteem, depression and anxiety symptoms among skeletal malocclusion patients” 45th Annual Meeting & Exhibition of AADR Los Angeles, USA, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    85)</dt><dd class="col-sm-9 col-9"> Yılmaz M.E., F.A.Başçiftçi, “Three-dimensional assessment of palatal vault after treatment with self-ligating bracket and rapid palatal expansion” 21st Congress of the Balkan Stomatological Society, Banja Luka, Bosnia and Herzegovina, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    86)</dt><dd class="col-sm-9 col-9"> İleri Z., F.A.Başçiftçi, “Effectiveness of Damon system as a self-ligating bracket” 21st Congress of the Balkan Stomatological Society, Banja Luka, Bosnia and Herzegovina, 2016
                          </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     87)</dt><dd class="col-sm-9 col-9"> Yurttadur G., F.A.Başçiftçi, “An evaluation of the effects of rapid maxillary expansion on voice function” 21st Congress of the Balkan Stomatological Society, Banja Luka, Bosnia and Herzegovina, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    88)</dt><dd class="col-sm-9 col-9"> Vural A., E.A. Erdur, F.A.Başçiftçi, “Orthodontic treatment of open bite malocclusion with mini screw: Case report” 21st Congress of the Balkan Stomatological Society, Banja Luka, Bosnia and Herzegovina, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    89)</dt><dd class="col-sm-9 col-9"> Erol M., F.A.Başçiftçi, “Maxillary deficiency treatment with hybrid hyrax appliance: Case report” 21st Congress of the Balkan Stomatological Society, Banja Luka, Bosnia and Herzegovina, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    90)</dt><dd class="col-sm-9 col-9"> Metin M.E., F.A.Başçiftçi, Z. İleri,“Treatment approach of a class II patient using Damon self ligating system: Case report” 21st Congress of the Balkan Stomatological Society, Banja Luka, Bosnia and Herzegovina, 2016
                          </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     91)</dt><dd class="col-sm-9 col-9"> Baka Z.M., F.A.Başçiftçi, S.Alp,“Distalization with mini-implant supported ez-slider: A case report” 21st Congress of the Balkan Stomatological Society, Banja Luka, Bosnia and Herzegovina, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    92)</dt><dd class="col-sm-9 col-9"> Yurttadur G., Z.İleri, F.A.Başçiftçi, “Modifiye Thurow apareyi ile anterior openbite’ın ortodontik tedavisi: Vaka raporu” 15. Uluslararası Türk Ortodonti Derneği Kongresi, Antalya, 2016
                          </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     93)</dt><dd class="col-sm-9 col-9"> Başçiftçi F.A., M.E.Yılmaz, “Kendinden bağlanan braket sistemi ve hızlı üst çene genişletmesi yapılan hastalarda üç boyutlu olarak palatal kubbenin değerlendirilmesi” 15. Uluslararası Türk Ortodonti Derneği Kongresi, Antalya, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    94)</dt><dd class="col-sm-9 col-9"> Orakçıoğlu H., M.Ersöz., F.A.Başçiftçi, “Malatya bölgesi popülasyonunda ortodontik anomalilerin angle sınıflamasına göre değerlendirilimesi ve uluslararası ölçek (ICON) indeksleri çerçevesinde ortodontik tedavi ihtiyaçlarının belirlenmesi” 15. Uluslararası Türk Ortodonti Derneği Kongresi, Antalya, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    95)</dt><dd class="col-sm-9 col-9"> Baka Z.M., E.A.Erdur, S.Alp, F.A.Başçiftçi, “Unilateral dudak damak yarığına sahip hastalarda faringeal havayolunun değerlendirilmesi” Dudak Damak Yarıkları Derneği 3. Uluslararası Kongresi, Konya, 2016
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    96)</dt><dd class="col-sm-9 col-9"> Ergin E., F.A.Başçiftçi “Treatment of class II malocclusion with twin block appliance and fixed orthodontic mechanics: case report” 22nd Congress of the Balkan Stomatological Society, Thessaloniki , Greece, 2017
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    97)</dt><dd class="col-sm-9 col-9"> Erdur E.A., S.Aşık, F.A.Başçiftçi “Class II non extraction patients treated with the forsus fatique resistant device” 22nd Congress of the Balkan Stomatological Society, Thessaloniki , Greece, 2017
</dd></div>
                            </p>
                        </div>
                        <div id="tab4" class="tabcontent">
                            <h3>Uluslararası Dergilerde Yayınlanmış Makaleler</h3>
                            <p><div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2"> 1)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A.  ve A.İ. Karaman, “The Effect of A Modified Acrylic Bonded Rapid Maxillary Expansion Appliance and Vertical Chin Cup on Dentofacial Structures,” The Angle Orthodontist, 72, 61-71 (2002).
                             </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   2)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., N. Mutlu, A.İ. Karaman, S. Malkoc, ve H. Küçükkolbasi, “Does the Timing and Method of Rapid Maxillary Expansion Have an Effect on The Changes in Nasal Dimensions?.” The Angle Orthodontist, 72, 118-123 (2002).
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   3)</dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, ve Ö. Polat, “Unilateral Distal Molar Movement Using an Implant-Supported Distal Jet Appliance (Case Report),” The Angle Orthodontist, 72, 167-174 (2002).
                             </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   4)</dt><dd class="col-sm-9 col-9"> Karaman, A.İ., F.A. Başçiftçi, İ.E. Gelgör, ve A. Demir, “Examination of Soft Tissue Changes After Rapid Maxillary Expansion,” World Journal of Orthodontics, 3, 217-222 (2002).
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   5)</dt><dd class="col-sm-9 col-9"> Demir, A., F.A. Başçiftçi, İ.E. Gelgör, ve A.İ. Karaman, “Maxillary Canine Transposition,” J. Clin. Orthod, 36, 35-37 (2002)
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   6)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., ve S. Üşümez, “Effects of Extraction and Nonextraction Treatment on Class I and Class II Subjects,” The Angle Orthodontist, 73, 36-42 (2003).
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   7)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., T. Uysal, A. Büyükerkmen, ve Z. Sarı, “The Effects Of Activator Treatment On The Craniofacial Structures Of Class II Division 1 Patients,” European Journal of Orthodontics, 25, 87-93 (2003)
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    8)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., T. Uysal, ve A. Büyükerkmen, “Determination of Holdaway Soft Tissue Norms in Anatolian Turkish Adults,” Am. J. Orthod. Dentofacial. Orthop. 123, 395-400 (2003)
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    9)</dt><dd class="col-sm-9 col-9"> Uysal, T., F.A. Basciftci, S. Üşümez, Z. Sarı, ve A. Büyükerkmen, “Can Previously Bleached Teeth be Bonded Safely?,” Am. J. Orthod. Dentofacial. Orthop, 123, 628-632 (2003)
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    10)</dt><dd class="col-sm-9 col-9"> Üşümez, S., H. İşeri, M. Orhan, ve F.A. Basciftci, “Effect of Maxillary Expansion on Nocturnal Enuresis,” The Angle Orthodontist, 73, 532-538 (2003).
                            </dd></div><div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     11)</dt><dd class="col-sm-9 col-9"> Sarı, Z., T. Uysal, S. Üşümez, ve F.A. Basciftci, “Rapid Maxillary Expansion. Is it Better in The Mixed or in The Permanent Dentition?,” The Angle Orthodontist, 73, 654-661 (2003).
                            </dd></div> <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    12) </dt><dd class="col-sm-9 col-9">Basciftci, F.A., T. Uysal, ve A. Büyükerkmen, “Craniofacial Structure of Anatolian Turkish  Adults with Normal Occlusions and Well-Balanced Faces,” Am. J. Orthod. Dentofacial. Orthop, 125, 366-372 (2004).
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    13)</dt><dd class="col-sm-9 col-9"> Doruk, C., A.A. Bıçakcı, F.A. Basciftci,  U. Agar, ve H. Babacan, “A Comparison of The Effects of Rapid Maxillary Expansion and Fan-Type Rapid Maxillary Expansion on Dentofacial Structures,” The Angle Orthodontist, 74, 184-194 (2004)
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   14)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., T. Uysal, A. Büyükerkmen, ve A. Demir, “The Influence of Extraction Treatment on Holdaway Soft-Tissue Measurements,” The Angle Orthodontist, 74, 167-173 (2004).
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   15)</dt><dd class="col-sm-9 col-9"> Basciftci F.A., H.H. Korkmaz, H. İşeri, ve S. Malkoç, “Biomechanical Evaluation of Mandibular Midline Distraction Osteogenesis by Using The Finite Element Method,” Am. J. Orthod. Dentofacial. Orthop, 125, 706-715 (2004).
                            </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   16)</dt><dd class="col-sm-9 col-9"> Uysal, T., Z. Sarı, S.I. Ramoglu, ve  F.A. Basciftci, “Relationships Between Dental and Skeletal Maturity in Turkish Subjects” The Angle Orthodontist, 74, 657-664 (2004).
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   17)</dt><dd class="col-sm-9 col-9"> Demir, A., T. Uysal, E. Guray, ve F.A. Basciftci, “The Relationship Between Bruxism and Occlusal Factors Among Seven- to 19-Year-Old Turkish Children” The Angle Orthodontist, 74, 672-676 (2004)
                           </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">   18)</dt><dd class="col-sm-9 col-9"> Usumez, S., T. Uysal, Z. Sarı, F.A. Basciftci, A.İ. Karaman, ve E. Guray, “The Effects of Early Preorthodontic Trainer Treatment on Class II, Division 1 Patients” The Angle Orthodontist, 74, 605-609 (2004).
                           </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    19)</dt><dd class="col-sm-9 col-9"> Demir A., T. Uysal, F.A. Basciftci, ve E. Guray, “The Association of Occlusal Factors With Masticatory Muscle Tenderness in 10- to 19-Year-Old Turkish Subjects” The Angle Orthodontist, 75, 40-46 (2005).
                         </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    20)</dt><dd class="col-sm-9 col-9"> Uysal T., Z. Sarı, F.A. Basciftci, ve B. Memili, “Intermaxillary Tooth Size Discrepancy and Malocclusion Is there a Relation?” The Angle Orthodontist 75, 208-213 (2005).
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    21)</dt><dd class="col-sm-9 col-9"> Demir A., T. Uysal, Z. Sari, ve F.A.Basciftci, “Effects of camouflage treatment on dentofacial structures in Class II division 1 mandibular retrognathic patients” Eur J Orthod. 27, 524-531 (2005).
                          </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">    22)</dt><dd class="col-sm-9 col-9"> Sener Y., T. Uysal, F.A. Basciftci, A. Demir, ve M.S. Botsali, “Conventional and high-intensity halogen light effects on polymerization shrinkage of orthodontic adhesives” The Angle Orthodontist 76, 677-681 (2006).
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     23)</dt><dd class="col-sm-9 col-9"> Uysal, T., S.I. Ramoglu, F.A. Basciftci, ve  Z. Sarı, “Chronologic age and skeletal maturation of the cervical vertebrae and hand-wrist: is there a relationship?” Am J Orthod Dentofacial Orthop 130, 622-628 (2006)
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     24)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., T. Uysal, Z. Sarı ve Ö. Inan, “Occlusal contacts with different retention procedures in 1-year follow-up period” Am J Orthod Dentofacial Orthop 131, 357-362 (2007)
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     25)</dt><dd class="col-sm-9 col-9"> Uysal, T., F.A. Basciftci, Y. Sener, M.S. Botsali, ve A. Demir, “Conventional and high intensity halogen light effects on water sorption and microhardness of orthodontic adhesives” The Angle Orthodontist 78, 134-139 (2008)
                        </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     26)</dt><dd class="col-sm-9 col-9"> Basciftci F.A., H.H. Korkmaz, S.Usumez, ve O. Eraslan, “Biomechanical evaluation of chincup treatment with various force vectors.” Am J Orthod Dentofacial Orthop 134, :773-781 (2008)
                        </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     27)</dt><dd class="col-sm-9 col-9"> Gürel, H.G., F.A. Basciftci, ve U. Arslan, “Transient bacteremia after removal of a bonded maxillary expansion appliance” Am J Orthod Dentofacial Orthop 135, 190-193 (2009)
                        </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     28)</dt><dd class="col-sm-9 col-9"> Uysal, T., F.A. Basciftci, ve Y. Goyenc, “New regression equations for mixed-dentition arch analysis in a Turkish sample with no Bolton tooth-size discrepancy” Am J Orthod Dentofacial Orthop 135, 343-348. (2009)
                         </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      29)</dt><dd class="col-sm-9 col-9"> Uysal, T., A. Yagci, F.A. Basciftci, ve Y. Sisman, “Standards of soft tissue Arnett analysis for surgical planning in Turkish adults” Eur J Orthod 31, 449-456 (2009)
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     30)</dt><dd class="col-sm-9 col-9"> Sarı, Z., T, Uysal, F.A. Basciftci, ve Ö. Inan, “Occlusal contact changes with removable and bonded retainers in a 1-year retention period” The Angle Orthodontist 79, 867-872. (2009)
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     31)</dt><dd class="col-sm-9 col-9"> Malkoc, S., F.A. Basciftci, M. Nur ve B. Catalbas,“Maxillary and mandibular mesiodistal tooth sizes among different malocclusions in a sample of the Turkish population” Eur J Orthod. 33,592-596 (2011)
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     32)</dt><dd class="col-sm-9 col-9"> Ileri, Z., F.A. Basciftci, S. Malkoc, ve S.I. Ramoglu, “Comparison of the outcomes of the lower incisor extraction, premolar extraction and non-extraction treatments.” Eur J Orthod. 34,681-685 (2012)
                         </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      33)</dt><dd class="col-sm-9 col-9"> Akın, M., ve F.A. Basciftci, “Can white spot lesions be treated effectively?” The Angle Orthodontist 82,770-775 (2012)
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     34)</dt><dd class="col-sm-9 col-9"> Sener, S., N, Unlu, F.A. Basciftci, ve G. Bozdag, “Bilateral geminated teeth with talon cusps: A case report. ” Eur J Dent. 6,440-444 (2012)
                        </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     35)</dt><dd class="col-sm-9 col-9"> Akin, M, S. Aksakalli, F.A. Basciftci, A. Demir, “The effect of tooth bleaching on the shear bond strength of orthodontic brackets using self-etching primer systems.” Eur J Dent 7,55-60 (2013)
                         </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">     36)</dt><dd class="col-sm-9 col-9"> Akın, M, O.Y. Ozyılmaz, T. Yavuz, F. Aykent, F.A. Basciftci, “Effect of Nd:YAG laser bleaching and antioxidizing agents on the shear bond strength of brackets.” Photomed Laser Surg. 31,365-70 (2013)
                         </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      37)</dt><dd class="col-sm-9 col-9"> Baka, Z.M., F.A. Basciftci, U. Arslan, “Effects of 2 bracket and ligation types on plaque retention: a quantitative microbiologic analysis with real-time polymerase chain reaction.” Am J Orthod Dentofacial Orthop. 144,260-7 (2013)
                         </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      38)</dt><dd class="col-sm-9 col-9"> Basciftci, F.A., M. Akin, Z. İleri, S. Bayram. “Long-term stability of dentoalveolar, skeletal, and soft tissue changes after non-extraction treatment with self-ligating system”  Korean J Orthod. 44,(3), 119-127 (2014)
                        </dd></div>  <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">       39)</dt><dd class="col-sm-9 col-9"> Akın M., Z.M. Baka, Z. İleri, F.A. Basciftci “Can demineralized enamel surfaces be bonded safely?.” Acta Odontologica Scandinavica. 72,283-9 (2014)
                       </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      40)</dt><dd class="col-sm-9 col-9"> Bayram, S., F.A. Basciftci, E.Kurar, “Relationship between P561T and C422F polymorphisms in growth hormone receptor gene and mandibular prognathism” The Angle Orthodontist 84,803-9 (2014)
                       </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      41)</dt><dd class="col-sm-9 col-9"> Demirtas H.K., M. Akın, Z. Ileri, F.A. Basciftci, “Shear-bond-strength of orthodontic brackets to aged nano-hybrid compositeresin surfaces using different surface preparation” Dent Mater J. 34(1):86-90. (2015)
                      </dd></div>     <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      42)</dt><dd class="col-sm-9 col-9"> Herguner A., E.A. Erdur, F.A. Basciftci, S. Herguner “Attention-deficit/hyperactivity disorder symptoms in children with traumatic dental injuries” Dent Traumatol. 31(2):140-3 (2015)
                      </dd></div>     <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      43)</dt><dd class="col-sm-9 col-9"> Ileri, Z., F.A. Basciftci “Asymmetric rapid maxillary expansion in true unilateral crossbite malocclusion: A prospective controlled clinical study” The Angle Orthodontist 85,245-252 (2015)
                      </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">       44)</dt><dd class="col-sm-9 col-9"> Akın M., M.Tezcan, Z.İleri, F.A. Basciftci, “Incidence of white spot lesions among patients treated with self- and conventional ligation systems” Clin Oral Invest 19(6):1501–1506 (2015)
                      </dd></div>     <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      45)</dt><dd class="col-sm-9 col-9"> Akin M, Z.M. Baka, Z. İleri, F.A. Basciftci, “Alveolar bone changes after asymmetric rapid maxillary expansion.” The Angle Orthodontist 85,799-805 (2015)
                       </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">       46)</dt><dd class="col-sm-9 col-9"> Erdur, E.A., F.A. Basciftci, “Effect of Ti:sapphire laser on shear bond strength of orthodontic brackets to ceramic surfaces.” Lasers Surg Med.  47,512-519 (2015)
                       </dd></div>   <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">       47)</dt><dd class="col-sm-9 col-9"> Erdur, E.A., F.A. Basciftci, “Effect of Ti:sapphire-femtosecond Laser on the Surface Roughness of Ceramics.” Lasers Surg Med. 47,833-838 (2015)
                      </dd></div>     <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      48)</dt><dd class="col-sm-9 col-9"> Akın, M., Y.E. Akgul, Z. Ileri, F.A. Basciftci “Three-dimensional evaluation of hybrid expander appliances: A pilot study” The Angle Orthodontist 86,81-86 (2016)
                      </dd></div>     <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">      49)</dt><dd class="col-sm-9 col-9"> İleri, Z., Z.M. Baka., M. Akın., S. Apillioğulları, , F.A. Basciftci “Effect of menstrual cycle on orthodontic pain perception: A controlled clinical trial” J Orofac Orthop. 77,168-175 (2016)
                      </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">       50)</dt><dd class="col-sm-9 col-9"> Altındiş, S., E. Toy, F.A. Basciftci “Effects of different rapid maxillary expansion appliances on facial soft tissues using three-dimensional imaging.” The Angle Orthodontist 86,590-598 (2016)
                      </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">       51)</dt><dd class="col-sm-9 col-9"> Baka, Z.M., M. Akın, Z. İleri, F.A. Basciftci “Effects of remineralization procedures on shear bond strengths of brackets bonded to demineralized enamel surfaces with self-etch systems.” The Angle Orthodontist 86,661-667 (2016)
                      </dd></div>    <div class="row mt-4 mt-lg-4"><dt class="col-lg-2 text-right col-2">       52)</dt><dd class="col-sm-9 col-9"> Yurttadur, G., F.A. Basciftci, K.Ozturk “The effects of rapid maxillary expansion on voice function” The Angle Orthodontist 87,49-55 (2017)
</dd></div>

                            </p>
                        </div>

                    </div>

                </div>

            </div>

        </div>
    </div>


@endsection
@section('css')
@endsection
@section('js')

    <script src="/components/plugins/greensock/TweenMax.min.js"></script>
    <script src="/components/plugins/greensock/TimelineMax.min.js"></script>
    <script src="/components/plugins/scrollmagic/ScrollMagic.min.js"></script>
    <script src="/components/plugins/greensock/animation.gsap.min.js"></script>
    <script src="/components/plugins/greensock/ScrollToPlugin.min.js"></script>
    <script src="/components/js/about.js"></script>
    <script>function openCity(evt, cityName) {




            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }





                document.getElementById(cityName).style.display = "block";
                evt.currentTarget.className += " active";
                  }</script>
@endsection
